# Generated by Django 3.2.3 on 2021-05-26 13:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarizer',
            name='time_summary_dict',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='summarizer',
            name='timestamp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None),
        ),
    ]
